### ISSUE TITLE
Video Undefined

### ISSUE THREAD

**Issue by mpaul31** [jonashartmann/webcam-directive#21]
i have to be missing something dumb here. in my on-streaming callback the passed in video param is always undefined even though i can see the video on the page. any ideas?

<webcam on-stream="onStream(stream,video)" on-streaming="onSuccess(video)"></webcam>

thanks!

**Comment by ceefour** [comment]
I think it's because you're using 2.0.0 instead of 1.2.0.

**Comment by krolow** [comment]
what is the solution to get video element in 2.0.0?

**Comment by anavgale** [comment]
I am getting error while using latest webcam with Angular 1.3.14 
---- Cannot read property 'width' of undefined
Always getting video undefined, I see video on my screen but inside on-streaming's callback method onSuccess(), $scope.mywebcam is undefined.

Here is how my directive defined as shown in latest documentation - 
<webcam class="well-small pull-right" on-stream="onStream(stream)" on-error="onError(err)" on-streaming="onSuccess()" video="mywebcam">

Can someone please point me to the right direction?

Thanks.

**Comment by cloyd** [comment]
same problem
$scope.mywebcam is undefined.
any updates?

**Comment by krolow** [comment]
are you guys using?

```coffee
angular.module "yourapp"
  .controller "YourCtrl",
    $scope.video = null

    $scope.onSuccess = () ->
      console.log $scope.video #not null after accept the webcam
```

```html
        <webcam
          on-stream="onStream(stream)"
          on-error="onError(err)"
          on-streaming="onSuccess()"
          video="video"></webcam>
```

here it works...

**Comment by jonashartmann** [comment]
I've made changes that should fix this issue. It required changing the interface of the directive, so I've pushed the version to 3.0.0
You should use the new channel attribute to bind the scopes: https://github.com/jonashartmann/webcam-directive#set-a-channel-to-bind-data

Please try it out and let me know if you still have issues.

**Comment by cloyd** [comment]
thanks @jonashartmann.
