### ISSUE TITLE
Expression 'undefined' used with directive 'webcam' is non-assignable!

### ISSUE THREAD

**Issue by jdjd1118** [jonashartmann/webcam-directive#24]
Keep getting this error when trying to access makeSnapshot().  Commenting out video: '=' under scope:{} gets rid of the error, but of course there's no video.

Any ideas?

Thanks

**Comment by Tuxity** [comment]
I started to update the documentation, not sure if it's the good way but work better. Check https://github.com/jonashartmann/webcam-directive/pull/25

**Comment by jonashartmann** [comment]
I've made changes that should fix this issue. It required changing the interface of the directive, so I've pushed the version to 3.0.0
You should use the new channel attribute to bind the scopes: https://github.com/jonashartmann/webcam-directive#set-a-channel-to-bind-data

Please try it out and let me know if you still have issues.
