### ISSUE TITLE
Webcam variable undefined if used in another tab

### ISSUE THREAD

**Issue by Tuxity** [jonashartmann/webcam-directive#26]
Despite of the documentation problems, if the webcam is used in another tab/window $scope.mywebcam (`video="mywebcam"`) is null

Tested with Chrome 40.X on OS X

**Comment by jonashartmann** [comment]
I've made changes that should fix this issue. It required changing the interface of the directive, so I've pushed the version to 3.0.0
You should use the new channel attribute to bind the scopes: https://github.com/jonashartmann/webcam-directive#set-a-channel-to-bind-data

Please try it out and let me know if you still have issues.
