### ISSUE TITLE
How do I save video stream ?

### ISSUE THREAD

**Issue by Koushikdutta** [jonashartmann/webcam-directive#27]
Hi,

How do I save video stream in local system or broadcast to Re5 or Wowza server ?

**Comment by jonashartmann** [comment]
You can access the video stream using the callbacks. After that it is up to you to do whatever you like with the data.
Maybe the answer in [this stackoverflow question](http://stackoverflow.com/questions/18509385/html-5-video-recording-and-storing-a-stream) can help you.
