### ISSUE TITLE
"Failed to allocate videosource" error in Firefox

### ISSUE THREAD

**Issue by chrismbarr** [jonashartmann/webcam-directive#28]
Currently if I go to [the demo page](http://jonashartmann.github.io/webcam-directive/#/) in FireFox, the video stream will fail to start.  Debugging though it, I get this error:

```
MediaStreamError {
    name: "SourceUnavailableError",
    message: "Failed to allocate videosource",
    constraintName: ""
}
```

I am using Firefox 36.0.4 (the latest as of right now).  This may not be an issue with your JavaScript at all, I did find [this recent bug report for Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1076742) which sounds related.  Just letting you know if you're not aware.

**Comment by Urauth** [comment]
Fixed the problem where Firefox wouldn't get sources from MediaStream today

https://github.com/sysart/webcam-directive

**Comment by chrismbarr** [comment]
@Urauth perhaps make that a pull request for this project?

**Comment by jonashartmann** [comment]
Great! A pull request would be very appreciated :) :+1:

**Comment by chrismbarr** [comment]
Has this been fixed?  I see that @Urauth's version has [this commit](https://github.com/sysart/webcam-directive/commit/4ccba65a637b66da8b14da42c5a15fbe1d60ac77) which says it fixes the issue, but it looks like this project has been updated since the issue was opened and I can't find the related code.

**Comment by jonashartmann** [comment]
@chrismbarr This has not been fixed yet. The commit does not update the unit tests, so that would be necessary to merge it in this main repo.
Any help would be appreciated there, since I don't have the time lately to do it.
Thanks!
