### ISSUE TITLE
Select Rear Camera in Android devices

### ISSUE THREAD

**Issue by nayaniitg** [jonashartmann/webcam-directive#29]
This is more of a question than issue. By default if you are using Chrome on Android, the front camera is selected. Is there any way to select the rear camera via some options or controls? Thanks

**Comment by jonashartmann** [comment]
Interesting question! Take a look at this question. I think it gives some options.
http://stackoverflow.com/questions/14610945/how-to-choose-input-video-device-for-webrtc

**Comment by nylki** [comment]
I succesfully accessed the rear cam with this fix:
https://github.com/jonashartmann/webcam-directive/pull/31

**Comment by Urauth** [comment]
Did a fork for our company where I fixed the issue. You can change Camera with attribute cameraid="0" or cameraid="1" for example. Nothing very special but works:

https://github.com/sysart/webcam-directive
