### ISSUE TITLE
how to emit events to stop start webcam

### ISSUE THREAD

**Issue by nylki** [jonashartmann/webcam-directive#32]
Hi there (I am busy, so the PR will be delayed :/)
However I have a quick question. You are listening for these events:

```
        $scope.$on('START_WEBCAM', startWebcam);
        $scope.$on('STOP_WEBCAM', stopWebcam);
```

I was not able to trigger them when switching the view with:
```
	$scope.$on('$ionicView.beforeLeave', function(){
		console.log("beforeleave");
		$scope.$emit('STOP_WEBCAM');

	});
```

I am new to angular, so I suppose I am doing something wrong here, maybe you can help :)

**Comment by nylki** [comment]
got it. 
`$scope.$broadcast('START_WEBCAM');`
However, when emiting START_WEBCAM, it is not visible although the pop-up, asking for permissions appears.

**Comment by nylki** [comment]
disregard that aswell. I accidentally trigger *START_WEBCAM* two times, thus creating two video tags, only the second tag shows the stream.

 `$ionicView.beforeLeave` seems to get triggered twice. :/

**Comment by brucelane** [comment]
thank you very much for this: $scope.$broadcast('STOP_WEBCAM') !

**Comment by yoda-yoda** [comment]
Hi @jonashartmann , how do you disable the camera? e.g when navigating to a different state?
