### ISSUE TITLE
"PermissionDeniedError" error with Chrome on Android device

### ISSUE THREAD

**Issue by fstiffo** [jonashartmann/webcam-directive#39]
the code is the simplest:

`<webcam on-error="onError(err)"></webcam>`

Chrome on the android phone does not ask for permission.

Any idea?

**Comment by jonashartmann** [comment]
Hi @fstiffo , this could be very likely related to your Chrome browser settings. Maybe you didn't give permission once in the past and Chrome remembers that and doesn't ask again.

**Comment by fstiffo** [comment]
thanks for the answer, but is not the case. I checked carefully given permissions and I try on different Android devices.

**Comment by Reptoh** [comment]
@jonashartmann  
Hi Jonas! Have some issue. It works fine locally, but when I deploy to heroku(for example) get error

The following error occured: 
NavigatorUserMediaError {name: "PermissionDeniedError", message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", constraintName: ""}

**Comment by wrjanan** [comment]
believe the error is because of the browser's security policies, localhost works because google chrome reads localhost as secure, https is required for non-local servers. not the expert in SSL certificates, though try adding https://urlofyoursite.com, it worked for me on my heroku deployment.

**Comment by jonashartmann** [comment]
Lack of SSL is the issue here. See https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features
