### ISSUE TITLE
Minified dist file isn't up to date

### ISSUE THREAD

**Issue by etiago** [jonashartmann/webcam-directive#40]
Hi @jonashartmann ,

I was making use of your webcam-directive package when I noticed that up until version 3.0.0, it would leave the webcam on even after the objects are destroyed.

This was fixed in 3.1.\* but unfortunately the minified file wasn't generated with these fixes.

Any chance you could run the grunt script to generate it so it is generated upstream and so I don't have to hack around it myself? :smile: I could submit a pull request but considering we're talking about minified and hard to read code, it's probably better if it's generated by the project owner.

Cheers,
Tiago

**Comment by juampick** [comment]
Yes same for me.. I found same thing. min.js version is not updated!

**Comment by jonashartmann** [comment]
That should've been fixed with #57
