### ISSUE TITLE
MediaStream.stop() is deprecated in new Browser (Chrome 47)

### ISSUE THREAD

**Issue by sfakir** [jonashartmann/webcam-directive#43]
Result:
The stream is still active after $destroy();

functionality should be given by:

```
        if(!stream.stop && stream.getTracks) {
          stream.stop = function(){
            this.getTracks().forEach(function (track) {
              track.stop();
            });
          };
        }
```

**Comment by yoda-yoda** [comment]
@sfakir it is good you noticed this, it is better you made an issue, it would be better if you make a Pull Request 😄

**Comment by marceloalejoc** [comment]
The minified file `dist/webcam.min.js` uses MediaStream.stop() function, but it is deprecated.
Using `app/scripts/webcam.js` no problem with MediaStream.stop(), I gues the problem is when is minfied.

**Comment by jonashartmann** [comment]
It should work now at 3.2.0
