### ISSUE TITLE
Save Camera Data

### ISSUE THREAD

**Issue by phanivaranasi** [jonashartmann/webcam-directive#47]
Hi,
I'm sending the camera image byte to server using API, I'm using Java to save my file stream in server.
Could any one suggest to save that byte array using java code.

Thanks
Krishna

**Comment by jonashartmann** [comment]
Thanks for opening an issue. 

That is easily solvable by [Google](https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=java%20save%20byte%20array%20to%20file) which leads into for example this one: https://www.mkyong.com/java/how-to-convert-array-of-bytes-into-file/

I hope you have fun using it :)
