### ISSUE TITLE
Change video URL

### ISSUE THREAD

**Issue by calraiden** [jonashartmann/webcam-directive#51]
Hi,

My channel:
```
    $scope.myChannel = {

    		// the fields below are all optional
    		videoHeight: 640,
    		videoWidth: 360,
    		video: null
    };  
```

My code:

`<webcam on-stream="onStream(stream)" on-access-denied="onError(err)" on-streaming="onSuccess()" channel="myChannel" class="pull-right"></webcam>`

When the video is created, it generates a URL, but my url is different.

`
<video class="webcam-live" autoplay src="blob:https://example.mydomain.com/23ee07ad-561e-4bg8-ac31" width="360" height="270"></video>`

`

How could I change the src URL?

**Comment by jonashartmann** [comment]
Why are you trying to change the src URL?
That is generated from the camera stream. See the code: https://github.com/jonashartmann/webcam-directive/blob/master/app/scripts/webcam.js#L85

**Comment by calraiden** [comment]
Thanks for the explanation and link.
