### ISSUE TITLE
Flash fallback mode?

### ISSUE THREAD

**Issue by kukac7** [jonashartmann/webcam-directive#52]
like [jhuckaby/webcamjs](https://github.com/jhuckaby/webcamjs)?

**Comment by jonashartmann** [comment]
Thanks for the suggestion. That library you linked has a broader scope than this one.
This is more about connecting the specifications of getUserMedia with Angular.
Adding a Flash fallback mode to it would be in my perspective out of its scope. I would be willing to discuss about it if you can provide a clean implementation of that. :)

Although, if you do need a Flash fallback, you could still check support in your application and switch this component by a Flash specific component.

**Comment by jonashartmann** [comment]
Closing, as Flash is clearly not a way to go and out of the scope of this library.
