### ISSUE TITLE
camera device is locked failing to throw error

### ISSUE THREAD

**Issue by osueboy** [jonashartmann/webcam-directive#53]
when camera is being used by another application Firefox throws this 

"The following error occured:  MediaStreamError { name: "NotReadableError", message: "Failed to allocate videosource", constraint: "", stack: "" }"

Which is good, but when i open an application that uses camera, then open chrome, i dont get this error so i dont know how to handle this, any advice?

**Comment by jonashartmann** [comment]
You could check for that error and handle it as needed.
