### ISSUE TITLE
Not working with  mozila

### ISSUE THREAD

**Issue by aanair08** [jonashartmann/webcam-directive#54]
When  I tried in mozila then I got this

navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia
The following error occured:  MediaStreamError { name: "NotReadableError", message: "Failed to allocate videosource", constraint: "", stack: "" }

**Comment by bruceslan1989** [comment]
Please, fix it!

**Comment by jonashartmann** [comment]
This should have been fixed with #67
