### ISSUE TITLE
ios safari not supported .

### ISSUE THREAD

**Issue by renjithkr1** [jonashartmann/webcam-directive#62]
please update for safari

**Comment by dkaranja** [comment]
@renjithkr1  Safari(v 11.0+) now supports webRTC. Update safari.
https://caniuse.com/#search=webrtc

**Comment by yoda-yoda** [comment]
@renjithkr1  Safari(v 11.0+) now supports webRTC. Update safari.
https://caniuse.com/#search=webrtc
