### ISSUE TITLE
Create new release with latest modern API

### ISSUE THREAD

**Issue by jonashartmann** [jonashartmann/webcam-directive#68]
A new release (tag) should be made and pushed into npm / bower / everywhere else.
The version in dist of the master branch already contains the latest code.

**Comment by danilodorgam** [comment]
@jonashartmann already made a new version (tag)?

**Comment by jniles** [comment]
@jonashartmann, any progress here?  We'd like to use the new version!

**Comment by danilodorgam** [comment]
@jonashartmann I would love to help with something, tell me if I can contribute anything

**Comment by jonashartmann** [comment]
✔️ Latest fixes applied to master
✔️ Updated to version 3.2.0
✔️ Created a tag on master for 3.2.0
✔️ Published 3.2.0 on npm

Apologies for the delay 😊
